### ISSUE TITLE
Can't add AppImages after latest update

### ISSUE THREAD

**Issue by ThatIcyPolarBear** [mijorus/gearlever#283]
When trying to add appimages to gear lever (3.3.1)  you get a TypeError, here is the console output:
```
user@host:~$ flatpak run it.mijorus.gearlever 
Logging to file /var/home/user/.var/app/it.mijorus.gearlever/cache/logs/gearlever.log
Traceback (most recent call last):
  File "/app/share/gearlever/gearlever/GearleverWindow.py", line 276, in on_open_file_chooser_response
    self.on_selected_local_file(list(selected_files))
  File "/app/share/gearlever/gearlever/GearleverWindow.py", line 149, in on_selected_local_file
    if len(files) == 1 and self.app_details.set_from_local_file(files[0]):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/AppDetails.py", line 145, in set_from_local_file
    list_element = appimage_provider.create_list_element_from_file(file)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AppImageProvider.create_list_element_from_file() missing 1 required positional argument: 'return_new_el'
```

Tried with multiple different appimages, always the same error and obviously doesn't result in the appimage being opened by the application. Doesn't matter if you click open or drag & drop or open it via open with in files. I also checked and it works fine in the previous version (3.3.0)

**Comment by haevalencia** [comment]
I can confirm the issue, using Gear Lever on Bluefin (Version: 42.20250525.4 / FROM Fedora Silverblue 42).

As a temporary solution, I disabled automatic updates of the app and rolled back to version 3.2.5 (2d7a5d22e253).

**Comment by ampelectrecuted** [comment]
Can reproduce on arch

**Comment by mijorus** [comment]
Hi there, the issue was fixed with version 3.3.2

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
